export const MockUsers = [
  {
    name: "Alice William",
    desc: "senior developer",
    userid: "Alice",
    email: "alicedev@trial.com",
    address: "Chicago, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "Bob Johnson",
    desc: "software engineer",
    userid: "Bob",
    email: "bobdev@trial.com",
    address: "New York, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "Charlie Brown",
    desc: "frontend developer",
    userid: "Charlie",
    email: "charliedev@trial.com",
    address: "Los Angeles, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "David Smith",
    desc: "backend developer",
    userid: "David",
    email: "davidsmith@trial.com",
    address: "San Francisco, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "Emma Davis",
    desc: "data scientist",
    userid: "Emma",
    email: "emmadavis@trial.com",
    address: "Seattle, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "Frank Wilson",
    desc: "UI/UX designer",
    userid: "Frank",
    email: "frankwilson@trial.com",
    address: "Boston, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "Grace Taylor",
    desc: "product manager",
    userid: "Grace",
    email: "gracetaylor@trial.com",
    address: "Austin, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "Henry Anderson",
    desc: "software engineer",
    userid: "Henry",
    email: "henryanderson@trial.com",
    address: "Denver, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "Isabella Martinez",
    desc: "frontend developer",
    userid: "Isabella",
    email: "isabellamartinez@trial.com",
    address: "Miami, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "Jack Thompson",
    desc: "backend developer",
    userid: "Jack",
    email: "jackthompson@trial.com",
    address: "Houston, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "Kate Lewis",
    desc: "data scientist",
    userid: "Kate",
    email: "katelewis@trial.com",
    address: "Philadelphia, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "Liam Turner",
    desc: "UI/UX designer",
    userid: "Liam",
    email: "liamturner@trial.com",
    address: "Portland, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "Mia Walker",
    desc: "product manager",
    userid: "Mia",
    email: "miawalker@trial.com",
    address: "San Diego, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "Noah Hill",
    desc: "software engineer",
    userid: "Noah",
    email: "noahhill@trial.com",
    address: "Dallas, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "Olivia Scott",
    desc: "frontend developer",
    userid: "Olivia",
    email: "oliviascott@trial.com",
    address: "Atlanta, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "Peter Green",
    desc: "backend developer",
    userid: "Peter",
    email: "petergreen@trial.com",
    address: "Phoenix, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "Quinn Turner",
    desc: "data scientist",
    userid: "Quinn",
    email: "quinnturner@trial.com",
    address: "Charlotte, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "Ryan Adams",
    desc: "UI/UX designer",
    userid: "Ryan",
    email: "ryanadams@trial.com",
    address: "Nashville, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "Sophia Baker",
    desc: "product manager",
    userid: "Sophia",
    email: "sophiabaker@trial.com",
    address: "Orlando, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "Thomas Clark",
    desc: "software engineer",
    userid: "Thomas",
    email: "thomasclark@trial.com",
    address: "Las Vegas, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: false,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "Yakraj Pariyar",
    desc: "Fullstack Developer",
    userid: "yakraj",
    email: "contact@yakraj.com",
    address: "Mumbai india",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
];

export const StoredMessages = [
  {
    id: 1,
    chatid: "alicethomas",
    chats: [
      {
        id: 1,
        userfrom: "Alice",
        userto: "Thomas",
        textmsg: "Hey Bob, how are you?",
        imagemsg: "",
        viewed: true,
        date: "2023-07-10",
      },
      {
        id: 2,
        userfrom: "Thomas",
        userto: "Alice",
        textmsg: "Hi Alice, I'm good! How about you?",
        imagemsg: "",
        viewed: true,
        date: "2023-07-10",
      },
      {
        id: 3,
        userfrom: "Alice",
        userto: "Thomas",
        textmsg: "I'm doing great, thanks for asking!",
        imagemsg: "",
        viewed: false,
        date: "2023-07-11",
      },
      {
        id: 4,
        userfrom: "Thomas",
        userto: "Alice",
        textmsg: "That's awesome to hear!",
        imagemsg: "",
        viewed: false,
        date: "2023-07-11",
      },
      {
        id: 5,
        userfrom: "Alice",
        userto: "Thomas",
        textmsg:
          "By the way, did you watch the latest episode of our favorite show?",
        imagemsg: "",
        viewed: true,
        date: "2023-07-11",
      },
      {
        id: 6,
        userfrom: "Thomas",
        userto: "Alice",
        textmsg: "Yes! It was mind-blowing! Can't wait for the next one!",
        imagemsg: "",
        viewed: true,
        date: "2023-07-12",
      },
      {
        id: 7,
        userfrom: "Alice",
        userto: "Thomas",
        textmsg: "I know, right? The plot twists are insane!",
        imagemsg: "",
        viewed: false,
        date: "2023-07-12",
      },
      {
        id: 8,
        userfrom: "Thomas",
        userto: "Alice",
        textmsg: "Absolutely! It keeps getting better with each episode.",
        imagemsg:
          "https://fastly.picsum.photos/id/0/200/200.jpg?hmac=RZmZI0kb9l_aRWHFyOZUGyc8xsyV30HOJX8a4wuHWkA",
        viewed: false,
        date: "2023-07-12",
      },
      {
        id: 9,
        userfrom: "Alice",
        userto: "Thomas",
        textmsg: "Hey, are you free this weekend? Let's catch up for coffee.",
        imagemsg:
          "https://fastly.picsum.photos/id/0/200/200.jpg?hmac=RZmZI0kb9l_aRWHFyOZUGyc8xsyV30HOJX8a4wuHWkA,https://fastly.picsum.photos/id/955/200/200.jpg?hmac=_m3ln1pswsR9s9hWuWrwY_O6N4wizKmukfhvyaTrkjE,https://fastly.picsum.photos/id/912/200/200.jpg?hmac=tYYyMFni6bya5yEVkwmmFekjWGedHVByLtPI5q1lcyw,https://fastly.picsum.photos/id/567/200/200.jpg?hmac=S36MAHt-ylBTK3Xv7FsIbcN71oDHJpgvjWRzbRiBb48",
        viewed: true,
        date: "2023-07-13",
      },
      {
        id: 10,
        userfrom: "Thomas",
        userto: "Alice",
        textmsg: "Sounds good! Saturday afternoon works for me. See you then!",
        imagemsg: "",
        viewed: true,
        date: "2023-07-13",
      },
      {
        id: 11,
        userfrom: "Alice",
        userto: "Thomas",
        textmsg: "Great! Let's meet at our favorite café at 2 PM.",
        imagemsg: "",
        viewed: false,
        date: "2023-07-13",
      },
      {
        id: 12,
        userfrom: "Thomas",
        userto: "Alice",
        textmsg: "Perfect! Looking forward to it.",
        imagemsg: "",
        viewed: false,
        date: "2023-07-14",
      },
      {
        id: 13,
        userfrom: "Alice",
        userto: "Thomas",
        textmsg: "Hey Bob, did you see the funny meme I sent you?",
        imagemsg: "",
        viewed: true,
        date: "2023-07-14",
      },
      {
        id: 14,
        userfrom: "Thomas",
        userto: "Alice",
        textmsg: "Yes, it cracked me up! You always find the best ones.",
        imagemsg: "",
        viewed: true,
        date: "2023-07-14",
      },
      {
        id: 15,
        userfrom: "Alice",
        userto: "Thomas",
        textmsg: "Glad you liked it! Laughter is the best medicine.",
        imagemsg: "",
        viewed: false,
        date: "2023-07-15",
      },
    ],
  },
  {
    id: 2,
    chatid: "aliceemma",
    chats: [
      {
        id: 1,
        userfrom: "Alice",
        userto: "Emma",
        textmsg: "Hey, are you free this weekend? Let's catch up for coffee.",
        imagemsg:
          "https://fastly.picsum.photos/id/0/200/200.jpg?hmac=RZmZI0kb9l_aRWHFyOZUGyc8xsyV30HOJX8a4wuHWkA,https://fastly.picsum.photos/id/955/200/200.jpg?hmac=_m3ln1pswsR9s9hWuWrwY_O6N4wizKmukfhvyaTrkjE,https://fastly.picsum.photos/id/912/200/200.jpg?hmac=tYYyMFni6bya5yEVkwmmFekjWGedHVByLtPI5q1lcyw,https://fastly.picsum.photos/id/567/200/200.jpg?hmac=S36MAHt-ylBTK3Xv7FsIbcN71oDHJpgvjWRzbRiBb48",
        viewed: true,
        date: "2023-07-13",
      },
      {
        id: 2,
        userfrom: "Emma",
        userto: "Alice",
        textmsg: "Sounds good! Saturday afternoon works for me. See you then!",
        imagemsg: "",
        viewed: true,
        date: "2023-07-13",
      },
      {
        id: 3,
        userfrom: "Alice",
        userto: "Emma",
        textmsg:
          "I'm glad you're available. It's been a while since we last met.",
        imagemsg: "",
        viewed: true,
        date: "2023-07-14",
      },
      {
        id: 4,
        userfrom: "Emma",
        userto: "Alice",
        textmsg: "Yes, it has! We should definitely catch up more often.",
        imagemsg: "",
        viewed: true,
        date: "2023-07-14",
      },
      {
        id: 5,
        userfrom: "Alice",
        userto: "Emma",
        textmsg:
          "Absolutely! How about trying out that new restaurant in town?",
        imagemsg: "",
        viewed: true,
        date: "2023-07-15",
      },
      {
        id: 6,
        userfrom: "Emma",
        userto: "Alice",
        textmsg: "That sounds like a plan. I've heard great things about it.",
        imagemsg: "",
        viewed: true,
        date: "2023-07-15",
      },
      {
        id: 7,
        userfrom: "Alice",
        userto: "Emma",
        textmsg:
          "Let's make a reservation for Saturday evening. What time works for you?",
        imagemsg: "",
        viewed: true,
        date: "2023-07-16",
      },
      {
        id: 8,
        userfrom: "Emma",
        userto: "Alice",
        textmsg: "I'm free after 7 PM. Does that work for you?",
        imagemsg: "",
        viewed: true,
        date: "2023-07-16",
      },
      {
        id: 9,
        userfrom: "Alice",
        userto: "Emma",
        textmsg:
          "Perfect! I'll make the reservation for 7:30 PM. See you there!",
        imagemsg: "",
        viewed: true,
        date: "2023-07-16",
      },
      {
        id: 10,
        userfrom: "Emma",
        userto: "Alice",
        textmsg: "Sounds good! Looking forward to it.",
        imagemsg: "",
        viewed: true,
        date: "2023-07-16",
      },
      {
        id: 11,
        userfrom: "Alice",
        userto: "Emma",
        textmsg: "Hey, did you see this article about the latest tech trends?",
        imagemsg: "",
        viewed: true,
        date: "2023-07-17",
      },
      {
        id: 12,
        userfrom: "Emma",
        userto: "Alice",
        textmsg: "No, I haven't. Can you send me the link?",
        imagemsg: "",
        viewed: true,
        date: "2023-07-17",
      },
      {
        id: 13,
        userfrom: "Alice",
        userto: "Emma",
        textmsg: "Sure, here's the link: [insert link here]",
        imagemsg: "",
        viewed: true,
        date: "2023-07-17",
      },
      {
        id: 14,
        userfrom: "Emma",
        userto: "Alice",
        textmsg: "Thanks! I'll check it out.",
        imagemsg: "",
        viewed: true,
        date: "2023-07-17",
      },
      {
        id: 15,
        userfrom: "Alice",
        userto: "Emma",
        textmsg:
          "Hey, I just found out about a concert happening next month. Are you interested?",
        imagemsg: "",
        viewed: true,
        date: "2023-07-18",
      },
      {
        id: 16,
        userfrom: "Emma",
        userto: "Alice",
        textmsg: "Definitely! Who's performing?",
        imagemsg: "",
        viewed: true,
        date: "2023-07-18",
      },
      {
        id: 17,
        userfrom: "Alice",
        userto: "Emma",
        textmsg:
          "It's a popular band called 'The Wanderers'. They're amazing live!",
        imagemsg: "",
        viewed: true,
        date: "2023-07-18",
      },
      {
        id: 18,
        userfrom: "Emma",
        userto: "Alice",
        textmsg: "I've heard of them. Count me in!",
        imagemsg: "",
        viewed: true,
        date: "2023-07-18",
      },
      {
        id: 19,
        userfrom: "Alice",
        userto: "Emma",
        textmsg: "Great! I'll get the tickets and let you know the details.",
        imagemsg: "",
        viewed: true,
        date: "2023-07-19",
      },
      {
        id: 20,
        userfrom: "Emma",
        userto: "Alice",
        textmsg: "Sounds like a plan. Looking forward to it!",
        imagemsg: "",
        viewed: true,
        date: "2023-07-19",
      },
    ],
  },
];

export const ChatArchive = [
  {
    id: 1,
    user1: "Alice",
    user2: "Thomas",
    lastmsg: "actully i want this.",
    recenttime: "Thu Aug 24 2023 05:49:00 GMT+0530 (India Standard Time)",
    chatid: "alicethomas",
    favourite: "true",
  },
  {
    id: 1,
    user1: "Alice",
    user2: "Emma",
    lastmsg: "actully i want this.",
    recenttime: "Thu Aug 24 2023 05:49:00 GMT+0530 (India Standard Time)",
    chatid: "aliceemma",
    favourite: "true",
  },
];
