export const MockUsers = [
  {
    name: "Alice William",
    desc: "senior developer",
    userid: "Alice",
    email: "alicedev@trial.com",
    address: "Chicago, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "Bob Johnson",
    desc: "software engineer",
    userid: "Bob",
    email: "bobdev@trial.com",
    address: "New York, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "Charlie Brown",
    desc: "frontend developer",
    userid: "Charlie",
    email: "charliedev@trial.com",
    address: "Los Angeles, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "David Smith",
    desc: "backend developer",
    userid: "David",
    email: "davidsmith@trial.com",
    address: "San Francisco, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "Emma Davis",
    desc: "data scientist",
    userid: "Emma",
    email: "emmadavis@trial.com",
    address: "Seattle, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "Frank Wilson",
    desc: "UI/UX designer",
    userid: "Frank",
    email: "frankwilson@trial.com",
    address: "Boston, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "Grace Taylor",
    desc: "product manager",
    userid: "Grace",
    email: "gracetaylor@trial.com",
    address: "Austin, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "Henry Anderson",
    desc: "software engineer",
    userid: "Henry",
    email: "henryanderson@trial.com",
    address: "Denver, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "Isabella Martinez",
    desc: "frontend developer",
    userid: "Isabella",
    email: "isabellamartinez@trial.com",
    address: "Miami, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "Jack Thompson",
    desc: "backend developer",
    userid: "Jack",
    email: "jackthompson@trial.com",
    address: "Houston, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "Kate Lewis",
    desc: "data scientist",
    userid: "Kate",
    email: "katelewis@trial.com",
    address: "Philadelphia, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "Liam Turner",
    desc: "UI/UX designer",
    userid: "Liam",
    email: "liamturner@trial.com",
    address: "Portland, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "Mia Walker",
    desc: "product manager",
    userid: "Mia",
    email: "miawalker@trial.com",
    address: "San Diego, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "Noah Hill",
    desc: "software engineer",
    userid: "Noah",
    email: "noahhill@trial.com",
    address: "Dallas, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "Olivia Scott",
    desc: "frontend developer",
    userid: "Olivia",
    email: "oliviascott@trial.com",
    address: "Atlanta, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "Peter Green",
    desc: "backend developer",
    userid: "Peter",
    email: "petergreen@trial.com",
    address: "Phoenix, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "Quinn Turner",
    desc: "data scientist",
    userid: "Quinn",
    email: "quinnturner@trial.com",
    address: "Charlotte, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "Ryan Adams",
    desc: "UI/UX designer",
    userid: "Ryan",
    email: "ryanadams@trial.com",
    address: "Nashville, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "Sophia Baker",
    desc: "product manager",
    userid: "Sophia",
    email: "sophiabaker@trial.com",
    address: "Orlando, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "Thomas Clark",
    desc: "software engineer",
    userid: "Thomas",
    email: "thomasclark@trial.com",
    address: "Las Vegas, U.S.",
    cover: "https://picsum.photos/200.jpg",
    onilne: false,
    avatar: "https://picsum.photos/200.jpg",
  },
  {
    name: "Yakraj Pariyar",
    desc: "Fullstack Developer",
    userid: "yakraj",
    email: "contact@yakraj.com",
    address: "Mumbai india",
    cover: "https://picsum.photos/200.jpg",
    onilne: true,
    avatar: "https://picsum.photos/200.jpg",
  },
];
export const ChatArchive = [
  {
    id: 1,
    user1: "Alice",
    user2: "Thomas",
    lastmsg: "actully i want this.",
    recenttime: "Thu Aug 24 2023 05:49:00 GMT+0530 (India Standard Time)",
    chatid: "yakrajthomas",
    favourite: "true",
  },
  {
    id: 1,
    user1: "Alice",
    user2: "Emma",
    lastmsg: "actully i want this.",
    recenttime: "Thu Aug 24 2023 05:49:00 GMT+0530 (India Standard Time)",
    chatid: "yakrajthomas",
    favourite: "true",
  },
];

export const FavouriteArchives = [
  "unknownman787",
  "isiah556",
  "jamesWilliam",
  "dhanisha568",
];
export const chattings = [
  {
    id: 1,
    userfrom: "Alice",
    userto: "Bob",
    textmsg: "Hey Bob, how are you?",
    imagemsg: "",
    viewed: true,
    date: "2023-07-10",
  },
  {
    id: 2,
    userfrom: "Bob",
    userto: "Alice",
    textmsg: "Hi Alice, I'm good! How about you?",
    imagemsg: "",
    viewed: true,
    date: "2023-07-10",
  },
  {
    id: 3,
    userfrom: "Alice",
    userto: "Bob",
    textmsg: "I'm doing great, thanks for asking!",
    imagemsg: "",
    viewed: false,
    date: "2023-07-11",
  },
  {
    id: 4,
    userfrom: "Bob",
    userto: "Alice",
    textmsg: "That's awesome to hear!",
    imagemsg: "",
    viewed: false,
    date: "2023-07-11",
  },
  {
    id: 5,
    userfrom: "Alice",
    userto: "Bob",
    textmsg:
      "By the way, did you watch the latest episode of our favorite show?",
    imagemsg: "",
    viewed: true,
    date: "2023-07-11",
  },
  {
    id: 6,
    userfrom: "Bob",
    userto: "Alice",
    textmsg: "Yes! It was mind-blowing! Can't wait for the next one!",
    imagemsg: "",
    viewed: true,
    date: "2023-07-12",
  },
  {
    id: 7,
    userfrom: "Alice",
    userto: "Bob",
    textmsg: "I know, right? The plot twists are insane!",
    imagemsg: "",
    viewed: false,
    date: "2023-07-12",
  },
  {
    id: 8,
    userfrom: "Bob",
    userto: "Alice",
    textmsg: "Absolutely! It keeps getting better with each episode.",
    imagemsg:
      "https://fastly.picsum.photos/id/0/200/200.jpg?hmac=RZmZI0kb9l_aRWHFyOZUGyc8xsyV30HOJX8a4wuHWkA",
    viewed: false,
    date: "2023-07-12",
  },
  {
    id: 9,
    userfrom: "Alice",
    userto: "Bob",
    textmsg: "Hey, are you free this weekend? Let's catch up for coffee.",
    imagemsg:
      "https://fastly.picsum.photos/id/0/200/200.jpg?hmac=RZmZI0kb9l_aRWHFyOZUGyc8xsyV30HOJX8a4wuHWkA,https://fastly.picsum.photos/id/955/200/200.jpg?hmac=_m3ln1pswsR9s9hWuWrwY_O6N4wizKmukfhvyaTrkjE,https://fastly.picsum.photos/id/912/200/200.jpg?hmac=tYYyMFni6bya5yEVkwmmFekjWGedHVByLtPI5q1lcyw,https://fastly.picsum.photos/id/567/200/200.jpg?hmac=S36MAHt-ylBTK3Xv7FsIbcN71oDHJpgvjWRzbRiBb48",
    viewed: true,
    date: "2023-07-13",
  },
  {
    id: 10,
    userfrom: "Bob",
    userto: "Alice",
    textmsg: "Sounds good! Saturday afternoon works for me. See you then!",
    imagemsg: "",
    viewed: true,
    date: "2023-07-13",
  },
  {
    id: 11,
    userfrom: "Alice",
    userto: "Bob",
    textmsg: "Great! Let's meet at our favorite café at 2 PM.",
    imagemsg: "",
    viewed: false,
    date: "2023-07-13",
  },
  {
    id: 12,
    userfrom: "Bob",
    userto: "Alice",
    textmsg: "Perfect! Looking forward to it.",
    imagemsg: "",
    viewed: false,
    date: "2023-07-14",
  },
  {
    id: 13,
    userfrom: "Alice",
    userto: "Bob",
    textmsg: "Hey Bob, did you see the funny meme I sent you?",
    imagemsg: "",
    viewed: true,
    date: "2023-07-14",
  },
  {
    id: 14,
    userfrom: "Bob",
    userto: "Alice",
    textmsg: "Yes, it cracked me up! You always find the best ones.",
    imagemsg: "",
    viewed: true,
    date: "2023-07-14",
  },
  {
    id: 15,
    userfrom: "Alice",
    userto: "Bob",
    textmsg: "Glad you liked it! Laughter is the best medicine.",
    imagemsg: "",
    viewed: false,
    date: "2023-07-15",
  },
];
